name: "Bitwarden Credentials Integration"
inputs:
  bw-access-token:
    description: BitWarden Access Token
    required: true
runs:
  using: composite
  steps:
    - name: Fetch Secrets from Bitwarden
      uses: bitwarden/sm-action@v3.0.0
      with:
        access_token: ${{ inputs.bw-access-token }}
        secrets: |
          60a7fb0c-5534-426d-baf3-b453013dbfa8 > YANDEX_CLOUD_OAUTH2_TOKEN
          56f5441b-55f4-494e-a44f-b453013d11e9 > ALGOLIA_APPLICATION_ID
          e7af9a48-fe20-4155-9ef6-b453013d7407 > ALGOLIA_SEARCH_API_KEY
          b4977ab8-ce56-4190-9e27-b453014fd2d1 > SANDBOX_GRADLE_CACHE_ENCRYPTION_KEY
          397e6835-43bd-45a6-a3df-b4530154334d > SANDBOX_JWT_SIGNING_KEY
          24ba98b3-7dd5-4921-b319-b45301555ac2 > SANDBOX_KUBE_CONFIG

          ac5b4a69-5eb3-485b-9637-b45301590074 > PRODUCTION_WEBSITE_HOST
