/*
 * Copyright (C) 2025-2026 Axelix Labs
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.axelixlabs.axelix.sbs.spring.core.persistence.entities.classreading;

import java.beans.PropertyDescriptor;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Method;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;
import java.util.function.Function;

import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.asm.ClassReader;
import org.springframework.asm.Type;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.BeansException;

/**
 * Inspects the bytecode of a JPA entity to find which of its associations are read by {@code toString()},
 * so a hand-written one is treated the same as one generated by Lombok. Calls are
 * followed only within the entity's own class hierarchy; anything outside it is left unanalyzed, so
 * the inspector prefers to stay silent over a false positive.
 *
 * @author Dmitry Mazurov
 */
public class EntityMethodsInspector {

    private static final Logger log = LoggerFactory.getLogger(EntityMethodsInspector.class);

    private static final String TO_STRING_METHOD = "toString()Ljava/lang/String;";

    private final Class<?> entityClass;
    private final String entityInternalName;
    private final Set<String> associationNames;

    private final List<String> hierarchy = new ArrayList<>();
    private final Map<MethodRef, MethodBody> bodies = new HashMap<>();
    private final Map<String, String> associationGetterKeys = new HashMap<>();
    private final Set<MethodRef> privateMethods = new HashSet<>();
    private boolean hierarchyCollected;

    public EntityMethodsInspector(Class<?> entityClass, Set<String> associationNames) {
        this.entityClass = entityClass;
        this.entityInternalName = Type.getInternalName(entityClass);
        this.associationNames = associationNames;
    }

    public Set<String> detectAssociationsReadByToString() {
        return detectAssociationsReadBy(TO_STRING_METHOD);
    }

    private Set<String> detectAssociationsReadBy(String methodKey) {
        if (associationNames.isEmpty()) {
            return Set.of();
        }

        collectHierarchy();

        MethodBody root = resolve(entityInternalName, methodKey);
        if (root == null) {
            return Set.of();
        }
        return readAssociations(root);
    }

    private void collectHierarchy() {
        if (hierarchyCollected) {
            return;
        }
        hierarchyCollected = true;

        forEachClassInHierarchy(type -> hierarchy.add(Type.getInternalName(type)));
        // the hierarchy must be fully known before any bytecode is read, so super.toString() resolves.
        forEachClassInHierarchy(this::readMethods);
        mapAssociationGetters();
    }

    private void mapAssociationGetters() {
        try {
            for (PropertyDescriptor property : BeanUtils.getPropertyDescriptors(entityClass)) {
                Method getter = property.getReadMethod();
                if (getter != null && associationNames.contains(property.getName())) {
                    associationGetterKeys.put(getter.getName() + Type.getMethodDescriptor(getter), property.getName());
                }
            }
        } catch (BeansException e) {
            log.warn(
                    "Could not introspect the getters of {}, property-access associations may be missed",
                    entityClass,
                    e);
        }
    }

    private void forEachClassInHierarchy(Consumer<Class<?>> action) {
        for (Class<?> type = entityClass; type != null && type != Object.class; type = type.getSuperclass()) {
            action.accept(type);
        }
    }

    private Set<String> readAssociations(MethodBody root) {
        Set<String> read = new HashSet<>();
        Set<MethodBody> visited = new HashSet<>();
        Deque<MethodBody> queue = new ArrayDeque<>();
        queue.add(root);

        while (!queue.isEmpty()) {
            MethodBody body = queue.poll();
            if (!visited.add(body)) {
                continue;
            }

            body.getReadFields().stream().filter(associationNames::contains).forEach(read::add);

            followCalls(body.getExactCalls(), MethodRef::owner, read, queue);
            followCalls(
                    body.getVirtualCalls(),
                    call -> privateMethods.contains(call) ? call.owner() : entityInternalName,
                    read,
                    queue);
        }
        return read;
    }

    private void followCalls(
            Set<MethodRef> calls, Function<MethodRef, String> startOwner, Set<String> read, Deque<MethodBody> queue) {
        for (MethodRef call : calls) {
            String property = associationGetterKeys.get(call.key());
            if (property != null) {
                read.add(property);
            }
            MethodBody target = resolve(startOwner.apply(call), call.key());
            if (target != null) {
                queue.add(target);
            }
        }
    }

    private @Nullable MethodBody resolve(String owner, String key) {
        for (int i = hierarchy.indexOf(owner); i >= 0 && i < hierarchy.size(); i++) {
            MethodBody candidate = bodies.get(new MethodRef(hierarchy.get(i), key));
            if (candidate != null) {
                return candidate;
            }
        }
        return null;
    }

    private void readMethods(Class<?> type) {
        String internalName = Type.getInternalName(type);
        ClassLoader classLoader =
                type.getClassLoader() != null ? type.getClassLoader() : ClassLoader.getSystemClassLoader();

        try (InputStream stream = classLoader.getResourceAsStream(internalName + ".class")) {
            if (stream == null) {
                log.warn("Could not find the bytecode of {}, association detection is skipped for it", internalName);
                return;
            }
            MethodBodyReadingClassVisitor visitor = new MethodBodyReadingClassVisitor(internalName, hierarchy);
            new ClassReader(stream).accept(visitor, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
            bodies.putAll(visitor.getBodies());
            privateMethods.addAll(visitor.getPrivateMethods());
        } catch (IOException | RuntimeException e) {
            log.warn("Could not read the bytecode of {}, association detection is skipped for it", internalName, e);
        }
    }
}
