version: 2
updates:
  # NPM
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/master/front-end"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/website"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/docs"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      docker-dependencies:
        patterns:
          - "*"