package com.axelixlabs.axelix.sbs.spring.core.transactions

import java.sql.Connection
import java.sql.PreparedStatement

/**
 * A {@link Connection} wrapper that replaces {@link PreparedStatement} instances
 * with proxies collecting query execution statistics.
 *
 * @author Sergey Cherkasov
 * @author Mikhail Polivakha
 */
class ProxyingConnection(
    private val delegate : Connection,
    private val statsCollector : QueriesRecorder
) : Connection by delegate {

    override fun prepareStatement(sql: String): PreparedStatement {
        return ProxyingPreparedStatement(sql, delegate.prepareStatement(sql), statsCollector)
    }

    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency),
            statsCollector
        )
    }

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int
    ): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability),
            statsCollector
        )
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, autoGeneratedKeys),
            statsCollector
        )
    }

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, columnIndexes),
            statsCollector
        )
    }

    override fun prepareStatement(sql: String, columnNames: Array<String>): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, columnNames),
            statsCollector
        )
    }
}
