/*
 * Copyright (C) 2025-2026 Axelix Labs
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.axelixlabs.axelix.sbs.spring.core.transactions

import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 * A {@link Connection} wrapper that replaces {@link PreparedStatement} instances
 * with proxies collecting query execution statistics.
 *
 * @author Sergey Cherkasov
 * @author Mikhail Polivakha
 */
class ProxyingConnection(
    private val delegate : Connection,
    private val statsCollector : QueriesRecorder
) : Connection by delegate {

    override fun prepareStatement(sql: String): PreparedStatement {
        return ProxyingPreparedStatement(sql, delegate.prepareStatement(sql), statsCollector)
    }

    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency),
            statsCollector
        )
    }

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int
    ): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability),
            statsCollector
        )
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, autoGeneratedKeys),
            statsCollector
        )
    }

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, columnIndexes),
            statsCollector
        )
    }

    override fun prepareStatement(sql: String, columnNames: Array<String>): PreparedStatement {
        return ProxyingPreparedStatement(
            sql,
            delegate.prepareStatement(sql, columnNames),
            statsCollector
        )
    }
}
