/*
 * Copyright (C) 2025-2026 Axelix Labs
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
import {
    EDependencyEcosystem,
    EDependencyNote,
    EPlatformSupportStatus,
    ESupportSignal,
    type IDependenciesAnalysis,
} from "@/models";

/**
 * Stand-in analysis the page renders until the backend endpoint behind {@code getDependenciesAnalysis} exists.
 *
 * TODO: Delete once the backend serves the dependency analysis.
 */
export const DEPENDENCIES_ANALYSIS_MOCK: IDependenciesAnalysis = {
    rootCoordinates: "com.acme:visits-service:4.7.2",
    analyzedAt: "2026-09-11T09:24:00Z",
    platform: {
        name: "Spring Boot",
        version: "3.2.4",
        line: "3.2.x",
        latestKnownLine: "3.5.x",
        status: EPlatformSupportStatus.OUT_OF_OSS_MAINTENANCE,
        releasedAt: "2023-11-23",
        ossSupportEndsAt: "2024-11-21",
        commercialSupportEndsAt: "2027-02-23",
        supportedTargetLine: "3.5.x",
        supportedTargetOssEndsAt: "2027-06-30",
    },
    dependencies: [
        {
            coordinates: "org.springframework.cloud:spring-cloud-sleuth-core",
            project: "Spring Cloud Sleuth",
            version: "3.1.11",
            ecosystem: EDependencyEcosystem.OBSERVABILITY,
            signal: {
                kind: ESupportSignal.DISCONTINUED,
                reason: "The project was discontinued after the 3.1.x line. Tracing moved into Micrometer Tracing, which Spring Boot autoconfigures from 3.0 onward. Nothing here receives fixes.",
                evidence: "Curated project registry · artifact archived, no release since Jan 2023",
                note: {
                    kind: EDependencyNote.SUPERSEDED_BY,
                    value: "io.micrometer:micrometer-tracing-bridge-brave",
                },
            },
            resolutionPath: [
                "org.springframework.cloud:spring-cloud-starter-sleuth:3.1.11",
                "org.springframework.cloud:spring-cloud-sleuth-instrumentation:3.1.11",
                "org.springframework.cloud:spring-cloud-sleuth-core:3.1.11",
            ],
            status: "Discontinued. Final release Jan 2023, no maintenance line of any kind.",
            referenceLabel: "Sleuth to Micrometer Tracing migration",
            referenceUrl: "https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide",
        },
        {
            coordinates: "com.netflix.hystrix:hystrix-core",
            project: "Hystrix",
            version: "1.5.18",
            ecosystem: EDependencyEcosystem.RESILIENCE,
            signal: {
                kind: ESupportSignal.DISCONTINUED,
                reason: "Hystrix stopped active development, and the Spring Cloud modules wrapping it were removed from the release train. It reaches this app four levels down, through an internal platform BOM.",
                evidence: "Curated project registry · upstream repository in maintenance freeze since 2018",
                note: {
                    kind: EDependencyNote.SUPERSEDED_BY,
                    value: "io.github.resilience4j:resilience4j-spring-boot3",
                },
            },
            resolutionPath: [
                "com.acme:platform-bom:4.2.0",
                "org.springframework.cloud:spring-cloud-starter-netflix-hystrix:2.2.10.RELEASE",
                "org.springframework.cloud:spring-cloud-netflix-hystrix:2.2.10.RELEASE",
                "com.netflix.hystrix:hystrix-core:1.5.18",
            ],
            status: "Discontinued. Last release 1.5.18, no successor from the same authors.",
            referenceLabel: "Spring Cloud Circuit Breaker",
            referenceUrl: "https://spring.io/projects/spring-cloud-circuitbreaker",
        },
        {
            coordinates: "net.sf.ehcache:ehcache",
            project: "Ehcache 2",
            version: "2.10.9.2",
            ecosystem: EDependencyEcosystem.PERSISTENCE,
            signal: {
                kind: ESupportSignal.DISCONTINUED,
                reason: "Ehcache 2.x is a closed line. Development moved to org.ehcache:ehcache 3.x, under a different group and a different API.",
                evidence: "Curated project registry · group net.sf.ehcache, last release Dec 2020",
                note: {
                    kind: EDependencyNote.SUPERSEDED_BY,
                    value: "org.ehcache:ehcache 3.x",
                },
            },
            resolutionPath: ["org.hibernate.orm:hibernate-ehcache:6.4.4.Final", "net.sf.ehcache:ehcache:2.10.9.2"],
            status: "Discontinued. The 2.x line receives no releases; 3.x is a separate artifact.",
            referenceLabel: "Ehcache 3 migration guide",
            referenceUrl: "https://www.ehcache.org/documentation/3.10/migration-guide.html",
        },
        {
            coordinates: "org.springframework.statemachine:spring-statemachine-core",
            project: "Spring State Machine",
            version: "3.2.1",
            ecosystem: EDependencyEcosystem.SPRING,
            signal: {
                kind: ESupportSignal.MAINTENANCE,
                reason: "The project is in maintenance mode: no feature development, releases only for critical fixes. Teams are expected to plan a move rather than build further on it.",
                evidence: "Curated project registry · project page states maintenance mode",
                note: {
                    kind: EDependencyNote.MIGRATION_NOTE,
                    value: "No portfolio successor — replacement is an architectural choice",
                },
            },
            resolutionPath: ["org.springframework.statemachine:spring-statemachine-core:3.2.1"],
            status: "Maintenance mode since 3.2.1 (Apr 2024). No roadmap for a 4.x line.",
            referenceLabel: "Spring State Machine project page",
            referenceUrl: "https://spring.io/projects/spring-statemachine",
        },
        {
            coordinates: "org.springframework.webflow:spring-webflow",
            project: "Spring Web Flow",
            version: "3.0.0",
            ecosystem: EDependencyEcosystem.SPRING,
            signal: {
                kind: ESupportSignal.MAINTENANCE,
                reason: "Web Flow has had no feature release since 3.0.0 and is kept alive for existing applications only.",
                evidence: "Curated project registry · no feature release since Feb 2022",
                note: null,
            },
            resolutionPath: ["org.springframework.webflow:spring-webflow:3.0.0"],
            status: "Maintenance mode. 3.0.0 released Feb 2022.",
            referenceLabel: "Spring Web Flow project page",
            referenceUrl: "https://spring.io/projects/spring-webflow",
        },
        {
            coordinates: "joda-time:joda-time",
            project: "Joda-Time",
            version: "2.12.7",
            ecosystem: EDependencyEcosystem.OTHER,
            signal: {
                kind: ESupportSignal.MAINTENANCE,
                reason: "Finished by its own authors: java.time covers its ground, and Joda-Time is maintained for compatibility rather than developed.",
                evidence: "Curated project registry · upstream README directs new work to java.time",
                note: {
                    kind: EDependencyNote.SUPERSEDED_BY,
                    value: "java.time (JDK 21)",
                },
            },
            resolutionPath: ["com.acme:platform-commons:2.8.1", "joda-time:joda-time:2.12.7"],
            status: "Maintenance mode. Still released, but explicitly superseded by java.time.",
            referenceLabel: "Joda-Time project notes",
            referenceUrl: "https://www.joda.org/joda-time/",
        },
        {
            coordinates: "org.springframework.boot:spring-boot-starter-web",
            project: "Spring Boot",
            version: "3.2.4",
            ecosystem: EDependencyEcosystem.SPRING,
            signal: null,
            resolutionPath: ["org.springframework.boot:spring-boot-starter-web:3.2.4"],
            status: "Actively developed. Version follows the platform row above.",
            referenceLabel: "Spring Boot reference",
            referenceUrl: "https://docs.spring.io/spring-boot/index.html",
        },
        {
            coordinates: "org.springframework:spring-webmvc",
            project: "Spring Framework",
            version: "6.1.5",
            ecosystem: EDependencyEcosystem.SPRING,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-web:3.2.4",
                "org.springframework:spring-webmvc:6.1.5",
            ],
            status: "Actively developed.",
            referenceLabel: "Spring Framework reference",
            referenceUrl: "https://docs.spring.io/spring-framework/reference/",
        },
        {
            coordinates: "org.springframework.security:spring-security-web",
            project: "Spring Security",
            version: "6.2.3",
            ecosystem: EDependencyEcosystem.SPRING,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-security:3.2.4",
                "org.springframework.security:spring-security-web:6.2.3",
            ],
            status: "Actively developed.",
            referenceLabel: "Spring Security reference",
            referenceUrl: "https://docs.spring.io/spring-security/reference/",
        },
        {
            coordinates: "org.springframework.kafka:spring-kafka",
            project: "Spring for Apache Kafka",
            version: "3.1.2",
            ecosystem: EDependencyEcosystem.SPRING,
            signal: null,
            resolutionPath: ["org.springframework.kafka:spring-kafka:3.1.2"],
            status: "Actively developed.",
            referenceLabel: "Spring for Apache Kafka reference",
            referenceUrl: "https://docs.spring.io/spring-kafka/reference/",
        },
        {
            coordinates: "org.hibernate.orm:hibernate-core",
            project: "Hibernate ORM",
            version: "6.4.4.Final",
            ecosystem: EDependencyEcosystem.PERSISTENCE,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-data-jpa:3.2.4",
                "org.hibernate.orm:hibernate-core:6.4.4.Final",
            ],
            status: "Actively developed.",
            referenceLabel: "Hibernate ORM releases",
            referenceUrl: "https://hibernate.org/orm/releases/",
        },
        {
            coordinates: "com.zaxxer:HikariCP",
            project: "HikariCP",
            version: "5.0.1",
            ecosystem: EDependencyEcosystem.PERSISTENCE,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-data-jpa:3.2.4",
                "org.springframework.boot:spring-boot-starter-jdbc:3.2.4",
                "com.zaxxer:HikariCP:5.0.1",
            ],
            status: "Actively developed.",
            referenceLabel: "HikariCP releases",
            referenceUrl: "https://github.com/brettwooldridge/HikariCP/releases",
        },
        {
            coordinates: "org.postgresql:postgresql",
            project: "PostgreSQL JDBC",
            version: "42.5.4",
            ecosystem: EDependencyEcosystem.PERSISTENCE,
            signal: null,
            resolutionPath: ["org.postgresql:postgresql:42.5.4"],
            status: "Actively developed.",
            referenceLabel: "pgJDBC changelog",
            referenceUrl: "https://jdbc.postgresql.org/changelogs/",
        },
        {
            coordinates: "org.flywaydb:flyway-core",
            project: "Flyway",
            version: "9.22.3",
            ecosystem: EDependencyEcosystem.PERSISTENCE,
            signal: null,
            resolutionPath: ["org.flywaydb:flyway-core:9.22.3"],
            status: "Actively developed.",
            referenceLabel: "Flyway release notes",
            referenceUrl: "https://documentation.red-gate.com/flyway/release-notes-and-older-versions",
        },
        {
            coordinates: "com.fasterxml.jackson.core:jackson-databind",
            project: "Jackson",
            version: "2.15.4",
            ecosystem: EDependencyEcosystem.SERIALIZATION,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-web:3.2.4",
                "org.springframework.boot:spring-boot-starter-json:3.2.4",
                "com.fasterxml.jackson.core:jackson-databind:2.15.4",
            ],
            status: "Actively developed.",
            referenceLabel: "Jackson release notes",
            referenceUrl: "https://github.com/FasterXML/jackson/wiki/Jackson-Releases",
        },
        {
            coordinates: "com.fasterxml.jackson.core:jackson-core",
            project: "Jackson",
            version: "2.15.4",
            ecosystem: EDependencyEcosystem.SERIALIZATION,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-json:3.2.4",
                "com.fasterxml.jackson.core:jackson-databind:2.15.4",
                "com.fasterxml.jackson.core:jackson-core:2.15.4",
            ],
            status: "Actively developed.",
            referenceLabel: "Jackson release notes",
            referenceUrl: "https://github.com/FasterXML/jackson/wiki/Jackson-Releases",
        },
        {
            coordinates: "ch.qos.logback:logback-classic",
            project: "Logback",
            version: "1.4.14",
            ecosystem: EDependencyEcosystem.LOGGING,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-web:3.2.4",
                "org.springframework.boot:spring-boot-starter-logging:3.2.4",
                "ch.qos.logback:logback-classic:1.4.14",
            ],
            status: "Actively developed.",
            referenceLabel: "Logback news",
            referenceUrl: "https://logback.qos.ch/news.html",
        },
        {
            coordinates: "org.slf4j:slf4j-api",
            project: "SLF4J",
            version: "2.0.12",
            ecosystem: EDependencyEcosystem.LOGGING,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-logging:3.2.4",
                "ch.qos.logback:logback-classic:1.4.14",
                "org.slf4j:slf4j-api:2.0.12",
            ],
            status: "Actively developed.",
            referenceLabel: "SLF4J news",
            referenceUrl: "https://www.slf4j.org/news.html",
        },
        {
            coordinates: "io.micrometer:micrometer-core",
            project: "Micrometer",
            version: "1.12.4",
            ecosystem: EDependencyEcosystem.OBSERVABILITY,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-actuator:3.2.4",
                "io.micrometer:micrometer-core:1.12.4",
            ],
            status: "Actively developed.",
            referenceLabel: "Micrometer releases",
            referenceUrl: "https://github.com/micrometer-metrics/micrometer/releases",
        },
        {
            coordinates: "org.apache.tomcat.embed:tomcat-embed-core",
            project: "Apache Tomcat",
            version: "10.1.19",
            ecosystem: EDependencyEcosystem.OTHER,
            signal: null,
            resolutionPath: [
                "org.springframework.boot:spring-boot-starter-web:3.2.4",
                "org.springframework.boot:spring-boot-starter-tomcat:3.2.4",
                "org.apache.tomcat.embed:tomcat-embed-core:10.1.19",
            ],
            status: "Actively developed.",
            referenceLabel: "Tomcat 10.1 changelog",
            referenceUrl: "https://tomcat.apache.org/tomcat-10.1-doc/changelog.html",
        },
        {
            coordinates: "org.apache.commons:commons-lang3",
            project: "Commons Lang",
            version: "3.12.0",
            ecosystem: EDependencyEcosystem.OTHER,
            signal: null,
            resolutionPath: ["org.apache.commons:commons-lang3:3.12.0"],
            status: "Actively developed.",
            referenceLabel: "Commons Lang releases",
            referenceUrl: "https://commons.apache.org/proper/commons-lang/release-notes/",
        },
        {
            coordinates: "com.auth0:java-jwt",
            project: "java-jwt",
            version: "4.2.1",
            ecosystem: EDependencyEcosystem.OTHER,
            signal: null,
            resolutionPath: ["com.auth0:java-jwt:4.2.1"],
            status: "Actively developed.",
            referenceLabel: "java-jwt releases",
            referenceUrl: "https://github.com/auth0/java-jwt/releases",
        },
        {
            coordinates: "org.mapstruct:mapstruct",
            project: "MapStruct",
            version: "1.5.5.Final",
            ecosystem: EDependencyEcosystem.OTHER,
            signal: null,
            resolutionPath: ["org.mapstruct:mapstruct:1.5.5.Final"],
            status: "Actively developed.",
            referenceLabel: "MapStruct releases",
            referenceUrl: "https://github.com/mapstruct/mapstruct/releases",
        },
        {
            coordinates: "org.yaml:snakeyaml",
            project: "SnakeYAML",
            version: "2.2",
            ecosystem: EDependencyEcosystem.SERIALIZATION,
            signal: null,
            resolutionPath: ["org.springframework.boot:spring-boot-starter:3.2.4", "org.yaml:snakeyaml:2.2"],
            status: "Actively developed.",
            referenceLabel: "SnakeYAML changes",
            referenceUrl: "https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes",
        },
    ],
};
