# AXELIX
server.port=8093
axelix.sbs.auth.jwt.algorithm=HMAC512
axelix.sbs.auth.jwt.signing-key=22573444698685aa77750b88ad6e99ef1f94a7a909bc7df63f7a80666208c201ab7a584e6e05e6c9d0aa94b723f843ff
axelix.sbs.discovery.instance-actuator-url=http://localhost:8093/actuator
axelix.sbs.discovery.master-url=http://localhost:8080/api/internal/service/register
axelix.sbs.discovery.instance-name-prefix=notification-service-gradle-sb-2
axelix.sbs.discovery.auto=true