name: "Build Frontend"
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./master/front-end/.nvmrc

    - run: npm ci
      working-directory: ./master/front-end
      shell: bash

    - run: npm run lint && npm run lint-css && npm run test
      working-directory: ./master/front-end
      shell: bash

    - run: npm run build
      working-directory: ./master/front-end
      shell: bash