# These are the settings for the local launch of Axelix Master
axelix:
  master:
    discovery:
      self-registration:
        enabled: true
        eviction:
          heartbeat-timeout: 45s
          schedule: "0 * * * * *"
      auto:
        enabled: false
        broadcast:
          schedule: "0 * * * * *"
        platform: kubernetes
        kubernetes:
          # Should be provided by the local-launch configuration
          kube-apiserver-url:
          # Should be set-up in local .env file or by any other means
          sa-token-path: ${SA_TOKEN_PATH:/home/mpolivaha/OpenSource/axelix/master/local/sa-token}
          ca-cert-path: ${CA_CERT_PATH:/home/mpolivaha/OpenSource/axelix/master/local/ca-cert}
          filters:
            namespaces: default
    auth:
      jwt:
        algorithm: HMAC512
        lifespan: 12h
        # Random singing key for local development
        signing-key: 22573444698685aa77750b88ad6e99ef1f94a7a909bc7df63f7a80666208c201ab7a584e6e05e6c9d0aa94b723f843ff
      options:
        local:
          enabled: true
        super-admin:
          credentials:
            username: admin
            password: admin
      cookie:
        secure: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: [ "health" ]

spring:
  datasource:
    url: "jdbc:sqlite:file:memdb?mode=memory&cache=shared"
