server:
  port: 8080

spring:
  cloud:
    config:
      enabled: ${axelix.master.config-server.enabled}
      uri: ${axelix.master.config-server.uri}
      label: ${axelix.master.config-server.label}
      name: ${axelix.master.config-server.name:${spring.application.name}}
      username: ${axelix.master.config-server.username}
      password: ${axelix.master.config-server.password}
      fail-fast: ${axelix.master.config-server.fail-fast}
  config:
    import: 'configserver:'
  application:
    name: axelix

axelix:
  master:
    config-server:
      enabled: true
      uri:
      label: master
      name:
      username:
      password:
      fail-fast: true