server:
  port: 8080

spring:
  application:
    name: axile
  mvc:
    servlet:
      path: /api/${spring.application.name}
  cloud:
    kubernetes:
      discovery:
        enabled: true
        discovery-server-url: https://kubernetes.default.svc
        all-namespaces: false
      client:
        trust-certs: true

management:
  endpoints:
    web:
      exposure:
        include: [ "health" ]
axile:
  master:
    discovery:
      auto: true
      execution-environment: k8s