spring:
  main:
    cloud-platform: kubernetes
  cloud:
    kubernetes:
      discovery:
        # Public IP of the k8s cluster control plane
        discovery-server-url: https://158.160.194.14:443
        namespaces: default
      # Should be set-up in local .env file or by any other means
      sa-token-path: C:\Prog\Project\axile\master\local\token
      ca-cert-path: C:\Prog\Project\axile\master\local\ca.cert