# These are the default settings for Axelix Master.
server:
  port: 8080

spring:
  application:
    name: axelix
  ai:
    mcp:
      server:
        protocol: streamable
        name: "axelix-mcp-server"
        # Ant-like value placeholder is substituted by Gradle resources task
        version: "@project.version@"
        streamable-http:
          mcp-endpoint: "/api/mcp"
  datasource:
    # TODO:
    #  We need to decide on how the end users will provide
    #  the location of the SQLite database along with the actual database choice and credentials for it.
    url: jdbc:sqlite:axelix.db

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: [ "health" ]

# TODO: we need to think about the design of properties in general
axelix:
  master:
    discovery:
      self-registration:
        eviction:
          heartbeat-timeout: 45s
          schedule: "0 * * * * *"
      auto:
        enabled: true
        broadcast:
          schedule: "0 * * * * *"
        platform: kubernetes
        kubernetes:
          kube-apiserver-url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}
          sa-token-path: /var/run/secrets/kubernetes.io/serviceaccount/token
          ca-cert-path: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          filters:
            namespaces: default
    auth:
      jwt:
        lifespan: 12h
      options:
        super-admin:
          enabled: true
          credentials:
            username: admin
            password: admin
      cookie:
        name: auth_token
        name-authority: authorities
        secure: false
