name: Backend Pull Requests

on:
  pull_request:
    branches: [ master ]
    paths:
      # Build logic, and application modules
      - 'master/**'
      - '!master/front-end/**'
      - 'sbs/**'
      - 'common/**'

      # Core Gradle build configuration
      - 'buildSrc/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'

      # Code quality, formatting, and license configurations
      - 'pmd.ruleset.xml'
      - '.editorconfig'
      - 'LICENSE'
      - 'LICENSE_HEADER'

concurrency:
  # Unique ID of the concurrency group, which cancels an already running workflow for this PR (if any)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check PR size
        uses: ./.github/actions/check-pr-size
        with:
          max-lines: '500'

  backend-build:
    runs-on: ubuntu-latest
    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_URL: ${{ secrets.NEXUS_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Backend
        uses: ./.github/actions/build-master
        with:
          gradle-cache-encryption-key: ''
