name: Backend Pull Requests

on:
  pull_request:
    paths:
      - 'master/**'
      - 'sbs/**'
      - 'common/**'
    branches: [ master ]

concurrency:
  # Unique ID of the concurrency group, which cancels an already running workflow for this PR (if any)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check PR size
        uses: ./.github/actions/check-pr-size
        with:
          max-lines: '500'

  backend-build:
    needs: check-pr-size
    runs-on: ubuntu-latest
    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_URL: ${{ secrets.NEXUS_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Loading Secrets
        uses: ./.github/actions/bitwarden
        with:
          bw-access-token: ${{ secrets.BW_ACCESS_TOKEN }}

      - name: Build Backend
        uses: ./.github/actions/build-master
        with:
          gradle-cache-enryption-key: ${{ env.SANDBOX_GRADLE_CACHE_ENCRYPTION_KEY }}
