name: Check Linked Issues Pull Requests

on:
  pull_request:
    paths:
      - 'master/**'
      - 'sbs/**'
      - 'common/**'
    branches: [ master ]

concurrency:
  # Unique ID of the concurrency group, which cancels an already running workflow for this PR (if any)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-linked-issues:
    # External contributors can open PRs without targeting a specific issue.
    #
    # OWNER - Author is the owner of the repository.
    # MEMBER - Author is a member of the organization that owns the repository.
    # COLLABORATOR - Author has been invited to collaborate on the repository.
    #
    # see https://docs.github.com/en/graphql/reference/issues#enums
    if: >-
      github.event.pull_request.author_association == 'OWNER' ||
      github.event.pull_request.author_association == 'MEMBER' ||
      github.event.pull_request.author_association == 'COLLABORATOR'
    runs-on: ubuntu-latest
    steps:
      - name: Check for linked issues
        uses: nearform-actions/github-action-check-linked-issues@v1
        with:
          exclude-labels: "refactoring, dependencies, docs, security"
