name: Check Linked Issues Pull Requests

on:
  pull_request:
    paths:
      - 'master/**'
      - 'sbs/**'
      - 'common/**'
    branches: [ master ]

concurrency:
  # Unique ID of the concurrency group, which cancels an already running workflow for this PR (if any)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-linked-issues:
    # External contributors can open PRs without targeting a specific issue.
    #
    # read  - Default access granted to anyone on a public repository, including external contributors.
    # write - Granted to org members, added collaborators, and the org owner.
    # admin - Granted to repository/organization administrators.
    #
    # see https://docs.github.com/en/rest/collaborators/collaborators#get-repository-permissions-for-a-user
    runs-on: ubuntu-latest
    steps:
      - name: Check author permission
        id: check-permission
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.event.pull_request.user.login }}

      - name: Check for linked issues
        if: steps.check-permission.outputs.require-result == 'true'
        uses: nearform-actions/github-action-check-linked-issues@v1
        with:
          exclude-labels: "refactoring, dependencies, docs, security"
