name: Build / Deploy to Testing Env

on:
  workflow_dispatch:
    inputs:
      helm_chart_branch:
        description: 'Helm chart branch name'
        required: false
        type: string
        default: 'main'
  push:
    branches: [ master ]
    paths:
      # CI/CD configuration
      - '.github/**'

      # Docker
      - 'Dockerfile'

      # Application modules
      - 'axelix-enterprise' # Tracks changes to the Git submodule pointer (gitlink)
      - 'common/**'
      - 'master/**'
      - 'sbs/**'

      # Playground projects
      - 'playgrounds/**'

      # Core Gradle build configuration
      - 'buildSrc/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'Makefile'

      # Code quality, formatting, and license configurations
      - 'pmd.ruleset.xml'
      - '.editorconfig'
      - 'LICENSE'
      - 'LICENSE_HEADER'

jobs:
  build-deploy-source:
    runs-on: ubuntu-latest
    env:
      YANDEX_CLOUD_OAUTH2_TOKEN: ${{ secrets.YANDEX_CLOUD_OAUTH2_TOKEN }}
      CR_URL: ${{ vars.CR_URL }}
      IMAGE_REPOSITORY: ${{ vars.CR_URL }}/${{ vars.CR_MASTER_REPOSITORY }}
      IMAGE_NAME: axelix
      # Use branch from workflow_dispatch input if provided, otherwise default to 'main'
      HELM_CHART_BRANCH: ${{ github.event.inputs.helm_chart_branch || 'main' }}

      # We need Nexus so that the playground repos have the place to pull the dependency from
      # These are needed in order to publish the final build artifacts into Nexus package registry
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_URL: ${{ secrets.NEXUS_URL }}
      NEXUS_HOST_PORT: ${{ secrets.NEXUS_HOST_PORT }}

      # OIDC Related settings
      AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_ENABLED: true
      AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_ISSUER_URI: ${{ secrets.OIDC_GOOGLE_ISSUER_URL }}
      AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_CLIENT_ID: ${{ secrets.OIDC_GOOGLE_CLIENT_ID }}
      AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_CLIENT_SECRET: ${{ secrets.OIDC_GOOGLE_CLIENT_SECRET }}
      AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_BASE_URL: ${{ secrets.OIDC_GOOGLE_REDIRECT_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Loading Secrets
        uses: ./.github/actions/bitwarden
        with:
          bw-access-token: ${{ secrets.BW_ACCESS_TOKEN }}

      # Java 25 will be installed at this step.
      - name: Build Backend
        uses: ./.github/actions/build-master
        with:
          deploy-to-nexus: true
          gradle-cache-encryption-key: ${{ env.SANDBOX_GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Set up Docker
        uses: docker/setup-docker-action@v5

      - name: Read Gradle Properties file
        uses: madhead/read-java-properties@4
        id: gradleProperties
        env:
          # We have to clear the JAVA_HOME here, since the read-java-properties
          # is a docker-based action, and it assumes to have its own JAVA_HOME, different from
          # the one that we set up above. Be invoking read-java-properties the JAVA_HOME from
          # the runner leaks into container, and overrides the correct JAVA_HOME for the container.
          # So we must clean it up explicitly
          JAVA_HOME: ""
        with:
          file: gradle.properties
          property: axelixVersion

      - name: Build Docker Image
        run: |
          docker build --tag $IMAGE_REPOSITORY/$IMAGE_NAME:${{ steps.gradleProperties.outputs.value }} --file Dockerfile .

      - name: Docker login to Yandex Cloud CR
        run: echo $YANDEX_CLOUD_OAUTH2_TOKEN | docker login --username oauth --password-stdin $CR_URL

      - name: Docker push to Yandex Cloud CR
        run: docker push $IMAGE_REPOSITORY/$IMAGE_NAME:${{ steps.gradleProperties.outputs.value }}

      - name: Docker logout
        run: docker logout

      - name: Checkout helm-charts repository
        uses: actions/checkout@v6
        with:
          repository: axelixlabs/helm-charts
          ref: ${{ env.HELM_CHART_BRANCH }}
          path: helm-charts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Helm
        uses: azure/setup-helm@v5.0.0
        with:
          version: v3.14.0

      - name: Deploy master to K8S
        working-directory: helm-charts/charts/axelix
        run: |
          mkdir -p ~/.kube
          touch ~/.kube/config
          echo "$SANDBOX_KUBE_CONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config
          helm upgrade \
            --set image.pullPolicy=Always \
            --set image.name=$IMAGE_REPOSITORY/$IMAGE_NAME \
            --set image.ref=${{ steps.gradleProperties.outputs.value }} \
            --set axelix.master.auth.jwt.signingKey=${{ env.SANDBOX_JWT_SIGNING_KEY }} \
            --set axelix.master.auth.jwt.algorithm=HMAC512 \
            --set axelix.master.auth.cookie.secure=false \
            --set axelix.master.auth.options.oauth2.enabled=${{ env.AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_ENABLED }} \
            --set axelix.master.auth.options.oauth2.issuerUri=${{ env.AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_ISSUER_URI }} \
            --set axelix.master.auth.options.oauth2.baseUrl=${{ env.AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_BASE_URL }}  \
            --set axelix.master.auth.options.oauth2.clientId=${{ env.AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_CLIENT_ID }} \
            --set axelix.master.auth.options.oauth2.clientSecret=${{ env.AXELIX_MASTER_AUTH_OPTIONS_OAUTH2_CLIENT_SECRET }} \
            --set axelix.master.auth.options.local.enabled=true \
            --set axelix.master.discovery.selfRegistration.enabled=true \
            --install axelix-master . \
            -f values.yaml
          
      - name: Build Playgrounds via Make
        env:
          AXELIX_SBS_AUTH_JWT_ALGORITHM: HMAC512
          AXELIX_SBS_AUTH_JWT_SIGNING_KEY: $SANDBOX_JWT_SIGNING_KEY
        run: |
          make build-playground BUILD_ALL_PLAYGROUNDS="true"

      - name: Deploy Playground Petclinic Maven SB 2
        uses: ./.github/actions/deploy-playground
        with:
          working-directory: playgrounds/petclinic-maven-sb-2
          cr-repository-path: ${{ vars.CR_PLAYGROUND_REPOSITORY }}/spring-petclinic-sb-2
          image-tag: petclinic-maven-sb-2:2.7.18-SNAPSHOT
          helm-release: petclinic-maven-sb-2

      - name: Deploy Playground Feature Service Maven SB 3
        uses: ./.github/actions/deploy-playground
        with:
          working-directory: playgrounds/feature-service-maven-sb-3
          cr-repository-path: ${{ vars.CR_PLAYGROUND_REPOSITORY }}/feature-service-sb-3
          image-tag: feature-service-maven-sb-3:0.0.2-SNAPSHOT
          helm-release: feature-service-maven-sb-3

  dispatch:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' }}
    needs: [build-deploy-source]
    strategy:
      matrix:
        playground_repo: [
          'axelixlabs/notification-service',
          'axelixlabs/spring-petclinic',
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Loading Secrets
        uses: ./.github/actions/bitwarden
        with:
          bw-access-token: ${{ secrets.BW_ACCESS_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ env.GITHUB_MASTER_ACCESS_TOKEN }}
          repository: ${{ matrix.playground_repo }}
          event-type: monorepo-backend-updated
