name: Deploy Docs

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Loading Secrets
        uses: ./.github/actions/bitwarden
        with:
          bw-access-token: ${{ secrets.BW_ACCESS_TOKEN }}

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Build
        working-directory: docs
        run: npm run build

      - name: Copy global resources to VM via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ env.PRODUCTION_WEBSITE_HOST }}
          username: ${{ env.PRODUCTION_WEBSITE_USER }}
          key: ${{ env.PRODUCTION_WEBSITE_PRIVATE_KEY }}
          source: "docker-compose.yml,infra/nginx"
          target: "/home/${{ env.PRODUCTION_WEBSITE_USER }}"

      - name: Copy build to VM via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ env.PRODUCTION_WEBSITE_HOST }}
          username: ${{ env.PRODUCTION_WEBSITE_USER }}
          key: ${{ env.PRODUCTION_WEBSITE_PRIVATE_KEY }}
          source: "docs/build,docs/Dockerfile"
          target: "/home/${{ env.PRODUCTION_WEBSITE_USER }}/axelix-docs"
          strip_components: 1

      - name: Build Docker image on server and restart container
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ env.PRODUCTION_WEBSITE_HOST }}
          username: ${{ env.PRODUCTION_WEBSITE_USER }}
          key: ${{ env.PRODUCTION_WEBSITE_PRIVATE_KEY }}
          script: |
            set -eux
            cd /home/${{ env.PRODUCTION_WEBSITE_USER }}
            sudo docker compose rm -f -s docs
            sudo docker compose up --build -d docs