name: Frontend Pull Requests

on:
  pull_request:
    paths:
      - 'front-end/**'
    branches: [ master ]

concurrency:
  # Unique ID of the concurrency group, which cancels an already running workflow for this PR (if any)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check PR size
        uses: ./.github/actions/check-pr-size
        with:
          max-lines: '400'

  frontend-build:
    needs: check-pr-size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Frontend
        uses: ./.github/actions/build-frontend
