name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git release tag (e.g., v1.0.1)'
        required: true
        type: string

env:
  USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_CONTAINER_REGISTRY: ghcr.io
  RELEASE_TAG: ${{ github.event.inputs.git_tag }}

jobs:
  build-and-test-backend:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17, 21, 25 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ env.RELEASE_TAG }}
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: ${{ matrix.java }}

      - name: Build and Test
        run: ./gradlew clean build

  release-artifacts:
    needs: [build-and-test-backend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VITE_APP_SOURCE_CODE_LINK: https://github.com/axelixlabs/axelix
      VITE_APP_ISSUE_TRACKER_LINK: https://github.com/axelixlabs/axelix/issues
      VITE_APP_LICENSE_LINK: https://www.gnu.org/licenses/lgpl-3.0.en.html
      # TODO: Later, change this link for it to point to the overall UI guide page
      VITE_APP_REFERENCE_GUIDE_LINK: https://axelix.io/docs/features/details
      VITE_APP_BLOG_LINK: https://axelix.io/blog/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ env.RELEASE_TAG }}
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '25'

      # Intentionally leaving the setup-gradle action for release pipeline to not introduce any cached behavior
      # and to create the release build from scratch.
      - name: Build Backend
        run: ./gradlew clean build sourcesJar javadocJar

      - name: Install frontend dependencies
        working-directory: front-end
        run: npm ci

      - name: Linting source files
        working-directory: front-end
        run: npm run lint

      - name: Linting CSS files
        working-directory: front-end
        run: npm run lint-css

      - name: Running tests
        working-directory: front-end
        run: npm run test

      - name: Create .env file
        working-directory: front-end
        run: |
          echo "VITE_APP_VERSION=${{ github.event.inputs.git_tag }}" >> .env
          echo "VITE_APP_SOURCE_CODE_LINK=${{ env.VITE_APP_SOURCE_CODE_LINK }}" >> .env
          echo "VITE_APP_ISSUE_TRACKER_LINK=${{ env.VITE_APP_ISSUE_TRACKER_LINK }}" >> .env
          echo "VITE_APP_LICENSE_LINK=${{ env.VITE_APP_LICENSE_LINK }}" >> .env.production
          echo "VITE_APP_REFERENCE_GUIDE_LINK=${{ env.VITE_APP_REFERENCE_GUIDE_LINK }}" >> .env
          echo "VITE_APP_BLOG_LINK=${{ env.VITE_APP_BLOG_LINK }}" >> .env

      - name: Build frontend
        working-directory: front-end
        run: npm run build

      - name: Clean-up .env
        working-directory: front-end
        run: rm .env

      - name: Set up Docker
        uses: docker/setup-docker-action@v5

      - name: Build Docker Image
        run: docker build --tag ${{ env.GITHUB_CONTAINER_REGISTRY }}/${{ github.repository_owner }}/axelix:${{ env.RELEASE_TAG }} --file Dockerfile .

      # ====================================================================================
      # Artifacts Publication, after all builds, linters, tests, and Docker pushes succeed.
      # ====================================================================================
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.GITHUB_CONTAINER_REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push to GitHub Container registry
        run: docker push ${{ env.GITHUB_CONTAINER_REGISTRY }}/${{ github.repository_owner }}/axelix:${{ env.RELEASE_TAG }}

      - name: Docker logout from GitHub Container Registry
        run: docker logout ${{ env.GITHUB_CONTAINER_REGISTRY }}

      - name: Publish to GitHub Packages
        run: ./gradlew publish

#        // TODO: Uncomment later
#      - name: Publish to Maven Central
#        run: ./gradlew publishGprPublicationToMavenCentralRepository